export const sportsKpis = {
  Handball: {
    KPIs: [
      "Goals scored",
      "Assists",
      "Saves (for goalkeepers)",
      "Successful passes",
      "Turnovers",
      "Fouls committed/received",
      "Shot accuracy",
    ],
    "Alternate KPIs": [
      "Three step jump",
      "9 meter shoot",
      "6 meter shoot",
      "Penalty shoot",
      "Dodging",
    ],
  },
  Basketball: {
    KPIs: [
      "Points scored",
      "Assists",
      "Rebounds (offensive/defensive)",
      "Steals",
      "Blocks",
      "Turnovers",
      "Field goal percentage",
      "Free throw percentage",
      "Three-point percentage",
    ],
    "Alternate KPIs": [
      "Ball Handling",
      "Shot Blocking",
      "Footwork",
      "Scoring",
      "3 Pt Shooting",
    ],
  },
  Skating: {
    KPIs: [
      "Time taken (for speed skating)",
      "Scores (for figure skating)",
      "Number of jumps/spins",
      "Difficulty level of routines",
      "Execution score",
    ],
    "Alternate KPIs": ["Agility", "Balance", "Coordination", "Flexibility"],
  },
  Football: {
    KPIs: [
      "Goals scored",
      "Assists",
      "Pass completion rate",
      "Tackles",
      "Saves (for goalkeepers)",
      "Distance covered",
      "Possession percentage",
      "Fouls committed/received",
    ],
    "Alternate KPIs": [
      "Dribbling",
      "Offense",
      "Defense",
      "Team dynamics",
      "Set pieces",
    ],
  },
  Cricket: {
    KPIs: [
      "Runs scored",
      "Wickets taken",
      "Strike rate (batting)",
      "Economy rate (bowling)",
      "Catches",
      "Stumpings (for wicketkeepers)",
      "Boundaries (4s and 6s)",
    ],
    "Alternate KPIs": [
      "Batting Average",
      "Strike rate",
      "Average Balls faced per innings",
      "6 Rate",
      "4 Rate",
      "Boundary Percent",
      "Average balls before the first boundary",
      "Bowled Rate",
      "Other Dismissals rate",
    ],
  },
  "Physical Activity": {
    KPIs: [
      "Steps taken",
      "Distance covered",
      "Calories burned",
      "Active minutes",
      "Heart rate",
      "Workout frequency",
    ],
    "Alternate KPIs": [
      "Static Postural Assessment",
      "Movement Screens",
      "Flexibility",
      "Muscular Endurance",
      "Cardiorespiratory Fitness",
      "Performance Assessments (power, speed, agility, quickness)",
    ],
  },
  Yoga: {
    KPIs: ["Balance", "Stretches", "Flexibility", "Core strength"],
  },
  Gym: {
    "Strength Training": [
      "Total Volume Lifted",
      "Max Lift",
      "Reps to Failure",
      "Strength Gains",
      "Lift Success Rate",
    ],
    "Endurance Training": [
      "Total Work Duration",
      "Heart Rate Recovery",
      "Cardio Intensity",
      "Distance Covered (Cardio)",
      "Work-to-Rest Ratio",
    ],
    Hypertrophy: [
      "Muscle Mass Increase",
      "Progressive Overload",
      "Set and Rep Volume",
      "Muscle Fatigue Rate",
    ],
    "Flexibility and Mobility": [
      "Range of Motion (ROM)",
      "Flexibility Gains",
      "Mobility Exercises",
    ],
    "Fat Loss and Body Composition": [
      "Body Fat Percentage",
      "Waist-to-Hip Ratio",
      "Caloric Deficit",
      "Total Calories Burned",
    ],
    "Power and Explosiveness": [
      "Power Output (in Watts)",
      "Vertical Jump Height",
      "Sprinting Time/Speed",
      "Broad Jump Distance",
    ],
    Recovery: [
      "Sleep Quality",
      "Muscle Soreness",
      "Heart Rate Variability",
      "Resting Heart Rate",
    ],
    "Overall Fitness": ["VO2 Max", "Functional Strength Tests", "Fitness Age"],
    "Workout Consistency": ["Frequency of Workouts", "Adherence Rate"],
  },
};
